config/routes.rb
Rails.application.routes.draw do
 resources :games do
   resources :moves, only: [:create]
 end
 root to: 'games#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
  before_validation(on: :create) do
    self.state = {
      0 => { 0 => nil, 1 => nil, 2 => nil },
      1 => { 0 => nil, 1 => nil, 2 => nil },
      2 => { 0 => nil, 1 => nil, 2 => nil }
    }
    self.current_player = [:x, :o].sample
  end

  after_update_commit { broadcast_update }

  def [](row, col)
    state[row.to_s][col.to_s]
  end

  def move!(row, col)
    #Initial state/player
    state[row.to_s][col.to_s] = current_player

    #change player
    self.current_player = current_player == "x" ? "o" : "x"
    self.save!
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
    @games = Game.all
  end

  def show
    @game = Game.find(params[:id])
  end

  def create
    @game = Game.where(
      :state => {
        0 => { 0 => nil, 1 => nil, 2 => nil },
        1 => { 0 => nil, 1 => nil, 2 => nil },
        2 => { 0 => nil, 1 => nil, 2 => nil }
      },
      :current_player => "x").last

    if @game.present?
      redirect_to @game
    else
      redirect_to Game.create
    end
    
  end
end

app/controllers/moves_controller.rb
class MovesController < ApplicationController

  def create
    @game = Game.find(params[:game_id])
    @game.move!(params[:row], params[:col])

    respond_to do |format|
      format.turbo_stream
      format.html {
        redirect_to @game
      }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/moves_helper.rb
module MovesHelper
end

app/views/games/_game.html.erb
<h3 class="text-center"><%= game.current_player %> Moves</h3>
<% 3.times do |row| %>
  <div class="rows"> 
    <% 3.times do |col| %>
      <span class="cells d-flex justify-content-center align-items-center">
       <% if !game[row, col].nil? %>
       <h1><%= game[row, col] %></h1>
        <% else %>
        <%= button_to ' ', game_moves_path(game), params: { row: row, col: col }, method: :post, :class => "btn btn-outline-light btn-block" %>
        <% end %>
      </span> 
    <% end %>
  </div>
<% end %>

app/views/games/index.html.erb
<main class="container d-flex flex-column justify-content-center align-items-center">
  <h1 class="my-5">Play Tic Tac Toe</h1>
    <form action ="/games" method="post">
      <input type ="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

      <input type="submit" value="New game" class="btn btn-danger">
    </form>
</main>

app/views/games/show.html.erb
<main class="container d-flex flex-column justify-content-center align-items-center">
  <h1 class="my-5">Let's play!</h1>
    <%= turbo_stream_from @game %>
    <section id="<%= dom_id(@game) %>">
      <%= render @game %>
    </section>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TicTacToe</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>